/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminPanelRouteImport } from './routes/admin._panel'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminPanelBillingRouteImport } from './routes/admin._panel.billing'
import { Route as AdminPanelCatalogRouteImport } from './routes/admin._panel.catalog'
import { Route as AdminPanelClientsRouteImport } from './routes/admin._panel.clients'
import { Route as AdminPanelDashboardRouteImport } from './routes/admin._panel.dashboard'
import { Route as AdminPanelDocumentsRouteImport } from './routes/admin._panel.documents'
import { Route as AdminPanelExpensesRouteImport } from './routes/admin._panel.expenses'
import { Route as AdminPanelInvoicesRouteImport } from './routes/admin._panel.invoices'
import { Route as AdminPanelPaymentsRouteImport } from './routes/admin._panel.payments'
import { Route as AdminPanelProjectsRouteImport } from './routes/admin._panel.projects'
import { Route as AdminPanelQuotationsRouteImport } from './routes/admin._panel.quotations'
import { Route as AdminPanelSettingsRouteImport } from './routes/admin._panel.settings'
import { Route as AdminPanelClientsClientIdRouteImport } from './routes/admin._panel.clients.$clientId'
import { Route as AdminPanelClientsNewRouteImport } from './routes/admin._panel.clients.new'
import { Route as AdminPanelInvoicesInvoiceIdRouteImport } from './routes/admin._panel.invoices.$invoiceId'
import { Route as AdminPanelInvoicesNewRouteImport } from './routes/admin._panel.invoices.new'
import { Route as AdminPanelProjectsProjectIdRouteImport } from './routes/admin._panel.projects.$projectId'
import { Route as AdminPanelProjectsNewRouteImport } from './routes/admin._panel.projects.new'
import { Route as AdminPanelQuotationsQuotationIdRouteImport } from './routes/admin._panel.quotations.$quotationId'
import { Route as AdminPanelQuotationsNewRouteImport } from './routes/admin._panel.quotations.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelRoute = AdminPanelRouteImport.update({
  id: '/admin/_panel',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelBillingRoute = AdminPanelBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelCatalogRoute = AdminPanelCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelClientsRoute = AdminPanelClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelDashboardRoute = AdminPanelDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelDocumentsRoute = AdminPanelDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelExpensesRoute = AdminPanelExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelInvoicesRoute = AdminPanelInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelPaymentsRoute = AdminPanelPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelProjectsRoute = AdminPanelProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelQuotationsRoute = AdminPanelQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelSettingsRoute = AdminPanelSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelClientsClientIdRoute =
  AdminPanelClientsClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => AdminPanelClientsRoute,
  } as any)
const AdminPanelClientsNewRoute = AdminPanelClientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPanelClientsRoute,
} as any)
const AdminPanelInvoicesInvoiceIdRoute =
  AdminPanelInvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => AdminPanelInvoicesRoute,
  } as any)
const AdminPanelInvoicesNewRoute = AdminPanelInvoicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPanelInvoicesRoute,
} as any)
const AdminPanelProjectsProjectIdRoute =
  AdminPanelProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AdminPanelProjectsRoute,
  } as any)
const AdminPanelProjectsNewRoute = AdminPanelProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPanelProjectsRoute,
} as any)
const AdminPanelQuotationsQuotationIdRoute =
  AdminPanelQuotationsQuotationIdRouteImport.update({
    id: '/$quotationId',
    path: '/$quotationId',
    getParentRoute: () => AdminPanelQuotationsRoute,
  } as any)
const AdminPanelQuotationsNewRoute = AdminPanelQuotationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPanelQuotationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminPanelRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/billing': typeof AdminPanelBillingRoute
  '/admin/catalog': typeof AdminPanelCatalogRoute
  '/admin/clients': typeof AdminPanelClientsRouteWithChildren
  '/admin/dashboard': typeof AdminPanelDashboardRoute
  '/admin/documents': typeof AdminPanelDocumentsRoute
  '/admin/expenses': typeof AdminPanelExpensesRoute
  '/admin/invoices': typeof AdminPanelInvoicesRouteWithChildren
  '/admin/payments': typeof AdminPanelPaymentsRoute
  '/admin/projects': typeof AdminPanelProjectsRouteWithChildren
  '/admin/quotations': typeof AdminPanelQuotationsRouteWithChildren
  '/admin/settings': typeof AdminPanelSettingsRoute
  '/admin/clients/$clientId': typeof AdminPanelClientsClientIdRoute
  '/admin/clients/new': typeof AdminPanelClientsNewRoute
  '/admin/invoices/$invoiceId': typeof AdminPanelInvoicesInvoiceIdRoute
  '/admin/invoices/new': typeof AdminPanelInvoicesNewRoute
  '/admin/projects/$projectId': typeof AdminPanelProjectsProjectIdRoute
  '/admin/projects/new': typeof AdminPanelProjectsNewRoute
  '/admin/quotations/$quotationId': typeof AdminPanelQuotationsQuotationIdRoute
  '/admin/quotations/new': typeof AdminPanelQuotationsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/billing': typeof AdminPanelBillingRoute
  '/admin/catalog': typeof AdminPanelCatalogRoute
  '/admin/clients': typeof AdminPanelClientsRouteWithChildren
  '/admin/dashboard': typeof AdminPanelDashboardRoute
  '/admin/documents': typeof AdminPanelDocumentsRoute
  '/admin/expenses': typeof AdminPanelExpensesRoute
  '/admin/invoices': typeof AdminPanelInvoicesRouteWithChildren
  '/admin/payments': typeof AdminPanelPaymentsRoute
  '/admin/projects': typeof AdminPanelProjectsRouteWithChildren
  '/admin/quotations': typeof AdminPanelQuotationsRouteWithChildren
  '/admin/settings': typeof AdminPanelSettingsRoute
  '/admin/clients/$clientId': typeof AdminPanelClientsClientIdRoute
  '/admin/clients/new': typeof AdminPanelClientsNewRoute
  '/admin/invoices/$invoiceId': typeof AdminPanelInvoicesInvoiceIdRoute
  '/admin/invoices/new': typeof AdminPanelInvoicesNewRoute
  '/admin/projects/$projectId': typeof AdminPanelProjectsProjectIdRoute
  '/admin/projects/new': typeof AdminPanelProjectsNewRoute
  '/admin/quotations/$quotationId': typeof AdminPanelQuotationsQuotationIdRoute
  '/admin/quotations/new': typeof AdminPanelQuotationsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_panel': typeof AdminPanelRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/_panel/billing': typeof AdminPanelBillingRoute
  '/admin/_panel/catalog': typeof AdminPanelCatalogRoute
  '/admin/_panel/clients': typeof AdminPanelClientsRouteWithChildren
  '/admin/_panel/dashboard': typeof AdminPanelDashboardRoute
  '/admin/_panel/documents': typeof AdminPanelDocumentsRoute
  '/admin/_panel/expenses': typeof AdminPanelExpensesRoute
  '/admin/_panel/invoices': typeof AdminPanelInvoicesRouteWithChildren
  '/admin/_panel/payments': typeof AdminPanelPaymentsRoute
  '/admin/_panel/projects': typeof AdminPanelProjectsRouteWithChildren
  '/admin/_panel/quotations': typeof AdminPanelQuotationsRouteWithChildren
  '/admin/_panel/settings': typeof AdminPanelSettingsRoute
  '/admin/_panel/clients/$clientId': typeof AdminPanelClientsClientIdRoute
  '/admin/_panel/clients/new': typeof AdminPanelClientsNewRoute
  '/admin/_panel/invoices/$invoiceId': typeof AdminPanelInvoicesInvoiceIdRoute
  '/admin/_panel/invoices/new': typeof AdminPanelInvoicesNewRoute
  '/admin/_panel/projects/$projectId': typeof AdminPanelProjectsProjectIdRoute
  '/admin/_panel/projects/new': typeof AdminPanelProjectsNewRoute
  '/admin/_panel/quotations/$quotationId': typeof AdminPanelQuotationsQuotationIdRoute
  '/admin/_panel/quotations/new': typeof AdminPanelQuotationsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/admin/'
    | '/admin/billing'
    | '/admin/catalog'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/documents'
    | '/admin/expenses'
    | '/admin/invoices'
    | '/admin/payments'
    | '/admin/projects'
    | '/admin/quotations'
    | '/admin/settings'
    | '/admin/clients/$clientId'
    | '/admin/clients/new'
    | '/admin/invoices/$invoiceId'
    | '/admin/invoices/new'
    | '/admin/projects/$projectId'
    | '/admin/projects/new'
    | '/admin/quotations/$quotationId'
    | '/admin/quotations/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/admin/billing'
    | '/admin/catalog'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/documents'
    | '/admin/expenses'
    | '/admin/invoices'
    | '/admin/payments'
    | '/admin/projects'
    | '/admin/quotations'
    | '/admin/settings'
    | '/admin/clients/$clientId'
    | '/admin/clients/new'
    | '/admin/invoices/$invoiceId'
    | '/admin/invoices/new'
    | '/admin/projects/$projectId'
    | '/admin/projects/new'
    | '/admin/quotations/$quotationId'
    | '/admin/quotations/new'
  id:
    | '__root__'
    | '/'
    | '/admin/_panel'
    | '/admin/login'
    | '/admin/'
    | '/admin/_panel/billing'
    | '/admin/_panel/catalog'
    | '/admin/_panel/clients'
    | '/admin/_panel/dashboard'
    | '/admin/_panel/documents'
    | '/admin/_panel/expenses'
    | '/admin/_panel/invoices'
    | '/admin/_panel/payments'
    | '/admin/_panel/projects'
    | '/admin/_panel/quotations'
    | '/admin/_panel/settings'
    | '/admin/_panel/clients/$clientId'
    | '/admin/_panel/clients/new'
    | '/admin/_panel/invoices/$invoiceId'
    | '/admin/_panel/invoices/new'
    | '/admin/_panel/projects/$projectId'
    | '/admin/_panel/projects/new'
    | '/admin/_panel/quotations/$quotationId'
    | '/admin/_panel/quotations/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminPanelRoute: typeof AdminPanelRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_panel': {
      id: '/admin/_panel'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_panel/billing': {
      id: '/admin/_panel/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminPanelBillingRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/catalog': {
      id: '/admin/_panel/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminPanelCatalogRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/clients': {
      id: '/admin/_panel/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminPanelClientsRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/dashboard': {
      id: '/admin/_panel/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminPanelDashboardRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/documents': {
      id: '/admin/_panel/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminPanelDocumentsRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/expenses': {
      id: '/admin/_panel/expenses'
      path: '/expenses'
      fullPath: '/admin/expenses'
      preLoaderRoute: typeof AdminPanelExpensesRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/invoices': {
      id: '/admin/_panel/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminPanelInvoicesRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/payments': {
      id: '/admin/_panel/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPanelPaymentsRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/projects': {
      id: '/admin/_panel/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminPanelProjectsRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/quotations': {
      id: '/admin/_panel/quotations'
      path: '/quotations'
      fullPath: '/admin/quotations'
      preLoaderRoute: typeof AdminPanelQuotationsRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/settings': {
      id: '/admin/_panel/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminPanelSettingsRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/clients/$clientId': {
      id: '/admin/_panel/clients/$clientId'
      path: '/$clientId'
      fullPath: '/admin/clients/$clientId'
      preLoaderRoute: typeof AdminPanelClientsClientIdRouteImport
      parentRoute: typeof AdminPanelClientsRoute
    }
    '/admin/_panel/clients/new': {
      id: '/admin/_panel/clients/new'
      path: '/new'
      fullPath: '/admin/clients/new'
      preLoaderRoute: typeof AdminPanelClientsNewRouteImport
      parentRoute: typeof AdminPanelClientsRoute
    }
    '/admin/_panel/invoices/$invoiceId': {
      id: '/admin/_panel/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/admin/invoices/$invoiceId'
      preLoaderRoute: typeof AdminPanelInvoicesInvoiceIdRouteImport
      parentRoute: typeof AdminPanelInvoicesRoute
    }
    '/admin/_panel/invoices/new': {
      id: '/admin/_panel/invoices/new'
      path: '/new'
      fullPath: '/admin/invoices/new'
      preLoaderRoute: typeof AdminPanelInvoicesNewRouteImport
      parentRoute: typeof AdminPanelInvoicesRoute
    }
    '/admin/_panel/projects/$projectId': {
      id: '/admin/_panel/projects/$projectId'
      path: '/$projectId'
      fullPath: '/admin/projects/$projectId'
      preLoaderRoute: typeof AdminPanelProjectsProjectIdRouteImport
      parentRoute: typeof AdminPanelProjectsRoute
    }
    '/admin/_panel/projects/new': {
      id: '/admin/_panel/projects/new'
      path: '/new'
      fullPath: '/admin/projects/new'
      preLoaderRoute: typeof AdminPanelProjectsNewRouteImport
      parentRoute: typeof AdminPanelProjectsRoute
    }
    '/admin/_panel/quotations/$quotationId': {
      id: '/admin/_panel/quotations/$quotationId'
      path: '/$quotationId'
      fullPath: '/admin/quotations/$quotationId'
      preLoaderRoute: typeof AdminPanelQuotationsQuotationIdRouteImport
      parentRoute: typeof AdminPanelQuotationsRoute
    }
    '/admin/_panel/quotations/new': {
      id: '/admin/_panel/quotations/new'
      path: '/new'
      fullPath: '/admin/quotations/new'
      preLoaderRoute: typeof AdminPanelQuotationsNewRouteImport
      parentRoute: typeof AdminPanelQuotationsRoute
    }
  }
}

interface AdminPanelClientsRouteChildren {
  AdminPanelClientsClientIdRoute: typeof AdminPanelClientsClientIdRoute
  AdminPanelClientsNewRoute: typeof AdminPanelClientsNewRoute
}

const AdminPanelClientsRouteChildren: AdminPanelClientsRouteChildren = {
  AdminPanelClientsClientIdRoute: AdminPanelClientsClientIdRoute,
  AdminPanelClientsNewRoute: AdminPanelClientsNewRoute,
}

const AdminPanelClientsRouteWithChildren =
  AdminPanelClientsRoute._addFileChildren(AdminPanelClientsRouteChildren)

interface AdminPanelInvoicesRouteChildren {
  AdminPanelInvoicesInvoiceIdRoute: typeof AdminPanelInvoicesInvoiceIdRoute
  AdminPanelInvoicesNewRoute: typeof AdminPanelInvoicesNewRoute
}

const AdminPanelInvoicesRouteChildren: AdminPanelInvoicesRouteChildren = {
  AdminPanelInvoicesInvoiceIdRoute: AdminPanelInvoicesInvoiceIdRoute,
  AdminPanelInvoicesNewRoute: AdminPanelInvoicesNewRoute,
}

const AdminPanelInvoicesRouteWithChildren =
  AdminPanelInvoicesRoute._addFileChildren(AdminPanelInvoicesRouteChildren)

interface AdminPanelProjectsRouteChildren {
  AdminPanelProjectsProjectIdRoute: typeof AdminPanelProjectsProjectIdRoute
  AdminPanelProjectsNewRoute: typeof AdminPanelProjectsNewRoute
}

const AdminPanelProjectsRouteChildren: AdminPanelProjectsRouteChildren = {
  AdminPanelProjectsProjectIdRoute: AdminPanelProjectsProjectIdRoute,
  AdminPanelProjectsNewRoute: AdminPanelProjectsNewRoute,
}

const AdminPanelProjectsRouteWithChildren =
  AdminPanelProjectsRoute._addFileChildren(AdminPanelProjectsRouteChildren)

interface AdminPanelQuotationsRouteChildren {
  AdminPanelQuotationsQuotationIdRoute: typeof AdminPanelQuotationsQuotationIdRoute
  AdminPanelQuotationsNewRoute: typeof AdminPanelQuotationsNewRoute
}

const AdminPanelQuotationsRouteChildren: AdminPanelQuotationsRouteChildren = {
  AdminPanelQuotationsQuotationIdRoute: AdminPanelQuotationsQuotationIdRoute,
  AdminPanelQuotationsNewRoute: AdminPanelQuotationsNewRoute,
}

const AdminPanelQuotationsRouteWithChildren =
  AdminPanelQuotationsRoute._addFileChildren(AdminPanelQuotationsRouteChildren)

interface AdminPanelRouteChildren {
  AdminPanelBillingRoute: typeof AdminPanelBillingRoute
  AdminPanelCatalogRoute: typeof AdminPanelCatalogRoute
  AdminPanelClientsRoute: typeof AdminPanelClientsRouteWithChildren
  AdminPanelDashboardRoute: typeof AdminPanelDashboardRoute
  AdminPanelDocumentsRoute: typeof AdminPanelDocumentsRoute
  AdminPanelExpensesRoute: typeof AdminPanelExpensesRoute
  AdminPanelInvoicesRoute: typeof AdminPanelInvoicesRouteWithChildren
  AdminPanelPaymentsRoute: typeof AdminPanelPaymentsRoute
  AdminPanelProjectsRoute: typeof AdminPanelProjectsRouteWithChildren
  AdminPanelQuotationsRoute: typeof AdminPanelQuotationsRouteWithChildren
  AdminPanelSettingsRoute: typeof AdminPanelSettingsRoute
}

const AdminPanelRouteChildren: AdminPanelRouteChildren = {
  AdminPanelBillingRoute: AdminPanelBillingRoute,
  AdminPanelCatalogRoute: AdminPanelCatalogRoute,
  AdminPanelClientsRoute: AdminPanelClientsRouteWithChildren,
  AdminPanelDashboardRoute: AdminPanelDashboardRoute,
  AdminPanelDocumentsRoute: AdminPanelDocumentsRoute,
  AdminPanelExpensesRoute: AdminPanelExpensesRoute,
  AdminPanelInvoicesRoute: AdminPanelInvoicesRouteWithChildren,
  AdminPanelPaymentsRoute: AdminPanelPaymentsRoute,
  AdminPanelProjectsRoute: AdminPanelProjectsRouteWithChildren,
  AdminPanelQuotationsRoute: AdminPanelQuotationsRouteWithChildren,
  AdminPanelSettingsRoute: AdminPanelSettingsRoute,
}

const AdminPanelRouteWithChildren = AdminPanelRoute._addFileChildren(
  AdminPanelRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminPanelRoute: AdminPanelRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
