/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicAboutRouteImport } from './routes/_public.about'
import { Route as PublicBedroomInteriorsRouteImport } from './routes/_public.bedroom-interiors'
import { Route as PublicCommercialInteriorDesignerSuratRouteImport } from './routes/_public.commercial-interior-designer-surat'
import { Route as PublicCommercialInteriorsRouteImport } from './routes/_public.commercial-interiors'
import { Route as PublicContactRouteImport } from './routes/_public.contact'
import { Route as PublicHomeInteriorDesignerSuratRouteImport } from './routes/_public.home-interior-designer-surat'
import { Route as PublicInteriorDesignRouteImport } from './routes/_public.interior-design'
import { Route as PublicInteriorDesignerSuratRouteImport } from './routes/_public.interior-designer-surat'
import { Route as PublicLivingRoomInteriorsRouteImport } from './routes/_public.living-room-interiors'
import { Route as PublicModularInteriorsRouteImport } from './routes/_public.modular-interiors'
import { Route as PublicModularKitchenRouteImport } from './routes/_public.modular-kitchen'
import { Route as PublicModularKitchenSuratRouteImport } from './routes/_public.modular-kitchen-surat'
import { Route as PublicOfficeInteriorsRouteImport } from './routes/_public.office-interiors'
import { Route as PublicResidentialInteriorsRouteImport } from './routes/_public.residential-interiors'
import { Route as PublicWardrobeDesignRouteImport } from './routes/_public.wardrobe-design'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminPanelRouteImport } from './routes/admin._panel'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as PublicBlogIndexRouteImport } from './routes/_public.blog.index'
import { Route as PublicProjectsIndexRouteImport } from './routes/_public.projects.index'
import { Route as PublicServicesIndexRouteImport } from './routes/_public.services.index'
import { Route as AdminPanelBillingRouteImport } from './routes/admin._panel.billing'
import { Route as AdminPanelCatalogRouteImport } from './routes/admin._panel.catalog'
import { Route as AdminPanelClientsRouteImport } from './routes/admin._panel.clients'
import { Route as AdminPanelDashboardRouteImport } from './routes/admin._panel.dashboard'
import { Route as AdminPanelDocumentsRouteImport } from './routes/admin._panel.documents'
import { Route as AdminPanelExpensesRouteImport } from './routes/admin._panel.expenses'
import { Route as AdminPanelInvoicesRouteImport } from './routes/admin._panel.invoices'
import { Route as AdminPanelPaymentsRouteImport } from './routes/admin._panel.payments'
import { Route as AdminPanelProjectsRouteImport } from './routes/admin._panel.projects'
import { Route as AdminPanelQuotationsRouteImport } from './routes/admin._panel.quotations'
import { Route as AdminPanelSettingsRouteImport } from './routes/admin._panel.settings'
import { Route as AdminPanelClientsClientIdRouteImport } from './routes/admin._panel.clients.$clientId'
import { Route as AdminPanelClientsNewRouteImport } from './routes/admin._panel.clients.new'
import { Route as AdminPanelInvoicesInvoiceIdRouteImport } from './routes/admin._panel.invoices.$invoiceId'
import { Route as AdminPanelInvoicesNewRouteImport } from './routes/admin._panel.invoices.new'
import { Route as AdminPanelProjectsProjectIdRouteImport } from './routes/admin._panel.projects.$projectId'
import { Route as AdminPanelProjectsNewRouteImport } from './routes/admin._panel.projects.new'
import { Route as AdminPanelQuotationsQuotationIdRouteImport } from './routes/admin._panel.quotations.$quotationId'
import { Route as AdminPanelQuotationsNewRouteImport } from './routes/admin._panel.quotations.new'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBedroomInteriorsRoute = PublicBedroomInteriorsRouteImport.update({
  id: '/bedroom-interiors',
  path: '/bedroom-interiors',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCommercialInteriorDesignerSuratRoute =
  PublicCommercialInteriorDesignerSuratRouteImport.update({
    id: '/commercial-interior-designer-surat',
    path: '/commercial-interior-designer-surat',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicCommercialInteriorsRoute =
  PublicCommercialInteriorsRouteImport.update({
    id: '/commercial-interiors',
    path: '/commercial-interiors',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicHomeInteriorDesignerSuratRoute =
  PublicHomeInteriorDesignerSuratRouteImport.update({
    id: '/home-interior-designer-surat',
    path: '/home-interior-designer-surat',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicInteriorDesignRoute = PublicInteriorDesignRouteImport.update({
  id: '/interior-design',
  path: '/interior-design',
  getParentRoute: () => PublicRoute,
} as any)
const PublicInteriorDesignerSuratRoute =
  PublicInteriorDesignerSuratRouteImport.update({
    id: '/interior-designer-surat',
    path: '/interior-designer-surat',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicLivingRoomInteriorsRoute =
  PublicLivingRoomInteriorsRouteImport.update({
    id: '/living-room-interiors',
    path: '/living-room-interiors',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicModularInteriorsRoute = PublicModularInteriorsRouteImport.update({
  id: '/modular-interiors',
  path: '/modular-interiors',
  getParentRoute: () => PublicRoute,
} as any)
const PublicModularKitchenRoute = PublicModularKitchenRouteImport.update({
  id: '/modular-kitchen',
  path: '/modular-kitchen',
  getParentRoute: () => PublicRoute,
} as any)
const PublicModularKitchenSuratRoute =
  PublicModularKitchenSuratRouteImport.update({
    id: '/modular-kitchen-surat',
    path: '/modular-kitchen-surat',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicOfficeInteriorsRoute = PublicOfficeInteriorsRouteImport.update({
  id: '/office-interiors',
  path: '/office-interiors',
  getParentRoute: () => PublicRoute,
} as any)
const PublicResidentialInteriorsRoute =
  PublicResidentialInteriorsRouteImport.update({
    id: '/residential-interiors',
    path: '/residential-interiors',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicWardrobeDesignRoute = PublicWardrobeDesignRouteImport.update({
  id: '/wardrobe-design',
  path: '/wardrobe-design',
  getParentRoute: () => PublicRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelRoute = AdminPanelRouteImport.update({
  id: '/admin/_panel',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicBlogIndexRoute = PublicBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProjectsIndexRoute = PublicProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicServicesIndexRoute = PublicServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminPanelBillingRoute = AdminPanelBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelCatalogRoute = AdminPanelCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelClientsRoute = AdminPanelClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelDashboardRoute = AdminPanelDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelDocumentsRoute = AdminPanelDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelExpensesRoute = AdminPanelExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelInvoicesRoute = AdminPanelInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelPaymentsRoute = AdminPanelPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelProjectsRoute = AdminPanelProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelQuotationsRoute = AdminPanelQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelSettingsRoute = AdminPanelSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelClientsClientIdRoute =
  AdminPanelClientsClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => AdminPanelClientsRoute,
  } as any)
const AdminPanelClientsNewRoute = AdminPanelClientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPanelClientsRoute,
} as any)
const AdminPanelInvoicesInvoiceIdRoute =
  AdminPanelInvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => AdminPanelInvoicesRoute,
  } as any)
const AdminPanelInvoicesNewRoute = AdminPanelInvoicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPanelInvoicesRoute,
} as any)
const AdminPanelProjectsProjectIdRoute =
  AdminPanelProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AdminPanelProjectsRoute,
  } as any)
const AdminPanelProjectsNewRoute = AdminPanelProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPanelProjectsRoute,
} as any)
const AdminPanelQuotationsQuotationIdRoute =
  AdminPanelQuotationsQuotationIdRouteImport.update({
    id: '/$quotationId',
    path: '/$quotationId',
    getParentRoute: () => AdminPanelQuotationsRoute,
  } as any)
const AdminPanelQuotationsNewRoute = AdminPanelQuotationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPanelQuotationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/about': typeof PublicAboutRoute
  '/bedroom-interiors': typeof PublicBedroomInteriorsRoute
  '/commercial-interior-designer-surat': typeof PublicCommercialInteriorDesignerSuratRoute
  '/commercial-interiors': typeof PublicCommercialInteriorsRoute
  '/contact': typeof PublicContactRoute
  '/home-interior-designer-surat': typeof PublicHomeInteriorDesignerSuratRoute
  '/interior-design': typeof PublicInteriorDesignRoute
  '/interior-designer-surat': typeof PublicInteriorDesignerSuratRoute
  '/living-room-interiors': typeof PublicLivingRoomInteriorsRoute
  '/modular-interiors': typeof PublicModularInteriorsRoute
  '/modular-kitchen': typeof PublicModularKitchenRoute
  '/modular-kitchen-surat': typeof PublicModularKitchenSuratRoute
  '/office-interiors': typeof PublicOfficeInteriorsRoute
  '/residential-interiors': typeof PublicResidentialInteriorsRoute
  '/wardrobe-design': typeof PublicWardrobeDesignRoute
  '/admin': typeof AdminPanelRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/billing': typeof AdminPanelBillingRoute
  '/admin/catalog': typeof AdminPanelCatalogRoute
  '/admin/clients': typeof AdminPanelClientsRouteWithChildren
  '/admin/dashboard': typeof AdminPanelDashboardRoute
  '/admin/documents': typeof AdminPanelDocumentsRoute
  '/admin/expenses': typeof AdminPanelExpensesRoute
  '/admin/invoices': typeof AdminPanelInvoicesRouteWithChildren
  '/admin/payments': typeof AdminPanelPaymentsRoute
  '/admin/projects': typeof AdminPanelProjectsRouteWithChildren
  '/admin/quotations': typeof AdminPanelQuotationsRouteWithChildren
  '/admin/settings': typeof AdminPanelSettingsRoute
  '/blog/': typeof PublicBlogIndexRoute
  '/projects/': typeof PublicProjectsIndexRoute
  '/services/': typeof PublicServicesIndexRoute
  '/admin/clients/$clientId': typeof AdminPanelClientsClientIdRoute
  '/admin/clients/new': typeof AdminPanelClientsNewRoute
  '/admin/invoices/$invoiceId': typeof AdminPanelInvoicesInvoiceIdRoute
  '/admin/invoices/new': typeof AdminPanelInvoicesNewRoute
  '/admin/projects/$projectId': typeof AdminPanelProjectsProjectIdRoute
  '/admin/projects/new': typeof AdminPanelProjectsNewRoute
  '/admin/quotations/$quotationId': typeof AdminPanelQuotationsQuotationIdRoute
  '/admin/quotations/new': typeof AdminPanelQuotationsNewRoute
}
export interface FileRoutesByTo {
  '/about': typeof PublicAboutRoute
  '/bedroom-interiors': typeof PublicBedroomInteriorsRoute
  '/commercial-interior-designer-surat': typeof PublicCommercialInteriorDesignerSuratRoute
  '/commercial-interiors': typeof PublicCommercialInteriorsRoute
  '/contact': typeof PublicContactRoute
  '/home-interior-designer-surat': typeof PublicHomeInteriorDesignerSuratRoute
  '/interior-design': typeof PublicInteriorDesignRoute
  '/interior-designer-surat': typeof PublicInteriorDesignerSuratRoute
  '/living-room-interiors': typeof PublicLivingRoomInteriorsRoute
  '/modular-interiors': typeof PublicModularInteriorsRoute
  '/modular-kitchen': typeof PublicModularKitchenRoute
  '/modular-kitchen-surat': typeof PublicModularKitchenSuratRoute
  '/office-interiors': typeof PublicOfficeInteriorsRoute
  '/residential-interiors': typeof PublicResidentialInteriorsRoute
  '/wardrobe-design': typeof PublicWardrobeDesignRoute
  '/admin': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/': typeof PublicIndexRoute
  '/admin/billing': typeof AdminPanelBillingRoute
  '/admin/catalog': typeof AdminPanelCatalogRoute
  '/admin/clients': typeof AdminPanelClientsRouteWithChildren
  '/admin/dashboard': typeof AdminPanelDashboardRoute
  '/admin/documents': typeof AdminPanelDocumentsRoute
  '/admin/expenses': typeof AdminPanelExpensesRoute
  '/admin/invoices': typeof AdminPanelInvoicesRouteWithChildren
  '/admin/payments': typeof AdminPanelPaymentsRoute
  '/admin/projects': typeof AdminPanelProjectsRouteWithChildren
  '/admin/quotations': typeof AdminPanelQuotationsRouteWithChildren
  '/admin/settings': typeof AdminPanelSettingsRoute
  '/blog': typeof PublicBlogIndexRoute
  '/projects': typeof PublicProjectsIndexRoute
  '/services': typeof PublicServicesIndexRoute
  '/admin/clients/$clientId': typeof AdminPanelClientsClientIdRoute
  '/admin/clients/new': typeof AdminPanelClientsNewRoute
  '/admin/invoices/$invoiceId': typeof AdminPanelInvoicesInvoiceIdRoute
  '/admin/invoices/new': typeof AdminPanelInvoicesNewRoute
  '/admin/projects/$projectId': typeof AdminPanelProjectsProjectIdRoute
  '/admin/projects/new': typeof AdminPanelProjectsNewRoute
  '/admin/quotations/$quotationId': typeof AdminPanelQuotationsQuotationIdRoute
  '/admin/quotations/new': typeof AdminPanelQuotationsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/bedroom-interiors': typeof PublicBedroomInteriorsRoute
  '/_public/commercial-interior-designer-surat': typeof PublicCommercialInteriorDesignerSuratRoute
  '/_public/commercial-interiors': typeof PublicCommercialInteriorsRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/home-interior-designer-surat': typeof PublicHomeInteriorDesignerSuratRoute
  '/_public/interior-design': typeof PublicInteriorDesignRoute
  '/_public/interior-designer-surat': typeof PublicInteriorDesignerSuratRoute
  '/_public/living-room-interiors': typeof PublicLivingRoomInteriorsRoute
  '/_public/modular-interiors': typeof PublicModularInteriorsRoute
  '/_public/modular-kitchen': typeof PublicModularKitchenRoute
  '/_public/modular-kitchen-surat': typeof PublicModularKitchenSuratRoute
  '/_public/office-interiors': typeof PublicOfficeInteriorsRoute
  '/_public/residential-interiors': typeof PublicResidentialInteriorsRoute
  '/_public/wardrobe-design': typeof PublicWardrobeDesignRoute
  '/admin/_panel': typeof AdminPanelRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/_panel/billing': typeof AdminPanelBillingRoute
  '/admin/_panel/catalog': typeof AdminPanelCatalogRoute
  '/admin/_panel/clients': typeof AdminPanelClientsRouteWithChildren
  '/admin/_panel/dashboard': typeof AdminPanelDashboardRoute
  '/admin/_panel/documents': typeof AdminPanelDocumentsRoute
  '/admin/_panel/expenses': typeof AdminPanelExpensesRoute
  '/admin/_panel/invoices': typeof AdminPanelInvoicesRouteWithChildren
  '/admin/_panel/payments': typeof AdminPanelPaymentsRoute
  '/admin/_panel/projects': typeof AdminPanelProjectsRouteWithChildren
  '/admin/_panel/quotations': typeof AdminPanelQuotationsRouteWithChildren
  '/admin/_panel/settings': typeof AdminPanelSettingsRoute
  '/_public/blog/': typeof PublicBlogIndexRoute
  '/_public/projects/': typeof PublicProjectsIndexRoute
  '/_public/services/': typeof PublicServicesIndexRoute
  '/admin/_panel/clients/$clientId': typeof AdminPanelClientsClientIdRoute
  '/admin/_panel/clients/new': typeof AdminPanelClientsNewRoute
  '/admin/_panel/invoices/$invoiceId': typeof AdminPanelInvoicesInvoiceIdRoute
  '/admin/_panel/invoices/new': typeof AdminPanelInvoicesNewRoute
  '/admin/_panel/projects/$projectId': typeof AdminPanelProjectsProjectIdRoute
  '/admin/_panel/projects/new': typeof AdminPanelProjectsNewRoute
  '/admin/_panel/quotations/$quotationId': typeof AdminPanelQuotationsQuotationIdRoute
  '/admin/_panel/quotations/new': typeof AdminPanelQuotationsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bedroom-interiors'
    | '/commercial-interior-designer-surat'
    | '/commercial-interiors'
    | '/contact'
    | '/home-interior-designer-surat'
    | '/interior-design'
    | '/interior-designer-surat'
    | '/living-room-interiors'
    | '/modular-interiors'
    | '/modular-kitchen'
    | '/modular-kitchen-surat'
    | '/office-interiors'
    | '/residential-interiors'
    | '/wardrobe-design'
    | '/admin'
    | '/admin/login'
    | '/admin/'
    | '/admin/billing'
    | '/admin/catalog'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/documents'
    | '/admin/expenses'
    | '/admin/invoices'
    | '/admin/payments'
    | '/admin/projects'
    | '/admin/quotations'
    | '/admin/settings'
    | '/blog/'
    | '/projects/'
    | '/services/'
    | '/admin/clients/$clientId'
    | '/admin/clients/new'
    | '/admin/invoices/$invoiceId'
    | '/admin/invoices/new'
    | '/admin/projects/$projectId'
    | '/admin/projects/new'
    | '/admin/quotations/$quotationId'
    | '/admin/quotations/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/bedroom-interiors'
    | '/commercial-interior-designer-surat'
    | '/commercial-interiors'
    | '/contact'
    | '/home-interior-designer-surat'
    | '/interior-design'
    | '/interior-designer-surat'
    | '/living-room-interiors'
    | '/modular-interiors'
    | '/modular-kitchen'
    | '/modular-kitchen-surat'
    | '/office-interiors'
    | '/residential-interiors'
    | '/wardrobe-design'
    | '/admin'
    | '/admin/login'
    | '/'
    | '/admin/billing'
    | '/admin/catalog'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/documents'
    | '/admin/expenses'
    | '/admin/invoices'
    | '/admin/payments'
    | '/admin/projects'
    | '/admin/quotations'
    | '/admin/settings'
    | '/blog'
    | '/projects'
    | '/services'
    | '/admin/clients/$clientId'
    | '/admin/clients/new'
    | '/admin/invoices/$invoiceId'
    | '/admin/invoices/new'
    | '/admin/projects/$projectId'
    | '/admin/projects/new'
    | '/admin/quotations/$quotationId'
    | '/admin/quotations/new'
  id:
    | '__root__'
    | '/_public'
    | '/_public/about'
    | '/_public/bedroom-interiors'
    | '/_public/commercial-interior-designer-surat'
    | '/_public/commercial-interiors'
    | '/_public/contact'
    | '/_public/home-interior-designer-surat'
    | '/_public/interior-design'
    | '/_public/interior-designer-surat'
    | '/_public/living-room-interiors'
    | '/_public/modular-interiors'
    | '/_public/modular-kitchen'
    | '/_public/modular-kitchen-surat'
    | '/_public/office-interiors'
    | '/_public/residential-interiors'
    | '/_public/wardrobe-design'
    | '/admin/_panel'
    | '/admin/login'
    | '/_public/'
    | '/admin/'
    | '/admin/_panel/billing'
    | '/admin/_panel/catalog'
    | '/admin/_panel/clients'
    | '/admin/_panel/dashboard'
    | '/admin/_panel/documents'
    | '/admin/_panel/expenses'
    | '/admin/_panel/invoices'
    | '/admin/_panel/payments'
    | '/admin/_panel/projects'
    | '/admin/_panel/quotations'
    | '/admin/_panel/settings'
    | '/_public/blog/'
    | '/_public/projects/'
    | '/_public/services/'
    | '/admin/_panel/clients/$clientId'
    | '/admin/_panel/clients/new'
    | '/admin/_panel/invoices/$invoiceId'
    | '/admin/_panel/invoices/new'
    | '/admin/_panel/projects/$projectId'
    | '/admin/_panel/projects/new'
    | '/admin/_panel/quotations/$quotationId'
    | '/admin/_panel/quotations/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminPanelRoute: typeof AdminPanelRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/bedroom-interiors': {
      id: '/_public/bedroom-interiors'
      path: '/bedroom-interiors'
      fullPath: '/bedroom-interiors'
      preLoaderRoute: typeof PublicBedroomInteriorsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/commercial-interior-designer-surat': {
      id: '/_public/commercial-interior-designer-surat'
      path: '/commercial-interior-designer-surat'
      fullPath: '/commercial-interior-designer-surat'
      preLoaderRoute: typeof PublicCommercialInteriorDesignerSuratRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/commercial-interiors': {
      id: '/_public/commercial-interiors'
      path: '/commercial-interiors'
      fullPath: '/commercial-interiors'
      preLoaderRoute: typeof PublicCommercialInteriorsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/home-interior-designer-surat': {
      id: '/_public/home-interior-designer-surat'
      path: '/home-interior-designer-surat'
      fullPath: '/home-interior-designer-surat'
      preLoaderRoute: typeof PublicHomeInteriorDesignerSuratRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/interior-design': {
      id: '/_public/interior-design'
      path: '/interior-design'
      fullPath: '/interior-design'
      preLoaderRoute: typeof PublicInteriorDesignRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/interior-designer-surat': {
      id: '/_public/interior-designer-surat'
      path: '/interior-designer-surat'
      fullPath: '/interior-designer-surat'
      preLoaderRoute: typeof PublicInteriorDesignerSuratRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/living-room-interiors': {
      id: '/_public/living-room-interiors'
      path: '/living-room-interiors'
      fullPath: '/living-room-interiors'
      preLoaderRoute: typeof PublicLivingRoomInteriorsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/modular-interiors': {
      id: '/_public/modular-interiors'
      path: '/modular-interiors'
      fullPath: '/modular-interiors'
      preLoaderRoute: typeof PublicModularInteriorsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/modular-kitchen': {
      id: '/_public/modular-kitchen'
      path: '/modular-kitchen'
      fullPath: '/modular-kitchen'
      preLoaderRoute: typeof PublicModularKitchenRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/modular-kitchen-surat': {
      id: '/_public/modular-kitchen-surat'
      path: '/modular-kitchen-surat'
      fullPath: '/modular-kitchen-surat'
      preLoaderRoute: typeof PublicModularKitchenSuratRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/office-interiors': {
      id: '/_public/office-interiors'
      path: '/office-interiors'
      fullPath: '/office-interiors'
      preLoaderRoute: typeof PublicOfficeInteriorsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/residential-interiors': {
      id: '/_public/residential-interiors'
      path: '/residential-interiors'
      fullPath: '/residential-interiors'
      preLoaderRoute: typeof PublicResidentialInteriorsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/wardrobe-design': {
      id: '/_public/wardrobe-design'
      path: '/wardrobe-design'
      fullPath: '/wardrobe-design'
      preLoaderRoute: typeof PublicWardrobeDesignRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_panel': {
      id: '/admin/_panel'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/blog/': {
      id: '/_public/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof PublicBlogIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/projects/': {
      id: '/_public/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof PublicProjectsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/services/': {
      id: '/_public/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof PublicServicesIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/_panel/billing': {
      id: '/admin/_panel/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminPanelBillingRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/catalog': {
      id: '/admin/_panel/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminPanelCatalogRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/clients': {
      id: '/admin/_panel/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminPanelClientsRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/dashboard': {
      id: '/admin/_panel/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminPanelDashboardRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/documents': {
      id: '/admin/_panel/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminPanelDocumentsRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/expenses': {
      id: '/admin/_panel/expenses'
      path: '/expenses'
      fullPath: '/admin/expenses'
      preLoaderRoute: typeof AdminPanelExpensesRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/invoices': {
      id: '/admin/_panel/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminPanelInvoicesRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/payments': {
      id: '/admin/_panel/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPanelPaymentsRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/projects': {
      id: '/admin/_panel/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminPanelProjectsRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/quotations': {
      id: '/admin/_panel/quotations'
      path: '/quotations'
      fullPath: '/admin/quotations'
      preLoaderRoute: typeof AdminPanelQuotationsRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/settings': {
      id: '/admin/_panel/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminPanelSettingsRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/clients/$clientId': {
      id: '/admin/_panel/clients/$clientId'
      path: '/$clientId'
      fullPath: '/admin/clients/$clientId'
      preLoaderRoute: typeof AdminPanelClientsClientIdRouteImport
      parentRoute: typeof AdminPanelClientsRoute
    }
    '/admin/_panel/clients/new': {
      id: '/admin/_panel/clients/new'
      path: '/new'
      fullPath: '/admin/clients/new'
      preLoaderRoute: typeof AdminPanelClientsNewRouteImport
      parentRoute: typeof AdminPanelClientsRoute
    }
    '/admin/_panel/invoices/$invoiceId': {
      id: '/admin/_panel/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/admin/invoices/$invoiceId'
      preLoaderRoute: typeof AdminPanelInvoicesInvoiceIdRouteImport
      parentRoute: typeof AdminPanelInvoicesRoute
    }
    '/admin/_panel/invoices/new': {
      id: '/admin/_panel/invoices/new'
      path: '/new'
      fullPath: '/admin/invoices/new'
      preLoaderRoute: typeof AdminPanelInvoicesNewRouteImport
      parentRoute: typeof AdminPanelInvoicesRoute
    }
    '/admin/_panel/projects/$projectId': {
      id: '/admin/_panel/projects/$projectId'
      path: '/$projectId'
      fullPath: '/admin/projects/$projectId'
      preLoaderRoute: typeof AdminPanelProjectsProjectIdRouteImport
      parentRoute: typeof AdminPanelProjectsRoute
    }
    '/admin/_panel/projects/new': {
      id: '/admin/_panel/projects/new'
      path: '/new'
      fullPath: '/admin/projects/new'
      preLoaderRoute: typeof AdminPanelProjectsNewRouteImport
      parentRoute: typeof AdminPanelProjectsRoute
    }
    '/admin/_panel/quotations/$quotationId': {
      id: '/admin/_panel/quotations/$quotationId'
      path: '/$quotationId'
      fullPath: '/admin/quotations/$quotationId'
      preLoaderRoute: typeof AdminPanelQuotationsQuotationIdRouteImport
      parentRoute: typeof AdminPanelQuotationsRoute
    }
    '/admin/_panel/quotations/new': {
      id: '/admin/_panel/quotations/new'
      path: '/new'
      fullPath: '/admin/quotations/new'
      preLoaderRoute: typeof AdminPanelQuotationsNewRouteImport
      parentRoute: typeof AdminPanelQuotationsRoute
    }
  }
}

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicBedroomInteriorsRoute: typeof PublicBedroomInteriorsRoute
  PublicCommercialInteriorDesignerSuratRoute: typeof PublicCommercialInteriorDesignerSuratRoute
  PublicCommercialInteriorsRoute: typeof PublicCommercialInteriorsRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicHomeInteriorDesignerSuratRoute: typeof PublicHomeInteriorDesignerSuratRoute
  PublicInteriorDesignRoute: typeof PublicInteriorDesignRoute
  PublicInteriorDesignerSuratRoute: typeof PublicInteriorDesignerSuratRoute
  PublicLivingRoomInteriorsRoute: typeof PublicLivingRoomInteriorsRoute
  PublicModularInteriorsRoute: typeof PublicModularInteriorsRoute
  PublicModularKitchenRoute: typeof PublicModularKitchenRoute
  PublicModularKitchenSuratRoute: typeof PublicModularKitchenSuratRoute
  PublicOfficeInteriorsRoute: typeof PublicOfficeInteriorsRoute
  PublicResidentialInteriorsRoute: typeof PublicResidentialInteriorsRoute
  PublicWardrobeDesignRoute: typeof PublicWardrobeDesignRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicBlogIndexRoute: typeof PublicBlogIndexRoute
  PublicProjectsIndexRoute: typeof PublicProjectsIndexRoute
  PublicServicesIndexRoute: typeof PublicServicesIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicBedroomInteriorsRoute: PublicBedroomInteriorsRoute,
  PublicCommercialInteriorDesignerSuratRoute:
    PublicCommercialInteriorDesignerSuratRoute,
  PublicCommercialInteriorsRoute: PublicCommercialInteriorsRoute,
  PublicContactRoute: PublicContactRoute,
  PublicHomeInteriorDesignerSuratRoute: PublicHomeInteriorDesignerSuratRoute,
  PublicInteriorDesignRoute: PublicInteriorDesignRoute,
  PublicInteriorDesignerSuratRoute: PublicInteriorDesignerSuratRoute,
  PublicLivingRoomInteriorsRoute: PublicLivingRoomInteriorsRoute,
  PublicModularInteriorsRoute: PublicModularInteriorsRoute,
  PublicModularKitchenRoute: PublicModularKitchenRoute,
  PublicModularKitchenSuratRoute: PublicModularKitchenSuratRoute,
  PublicOfficeInteriorsRoute: PublicOfficeInteriorsRoute,
  PublicResidentialInteriorsRoute: PublicResidentialInteriorsRoute,
  PublicWardrobeDesignRoute: PublicWardrobeDesignRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicBlogIndexRoute: PublicBlogIndexRoute,
  PublicProjectsIndexRoute: PublicProjectsIndexRoute,
  PublicServicesIndexRoute: PublicServicesIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminPanelClientsRouteChildren {
  AdminPanelClientsClientIdRoute: typeof AdminPanelClientsClientIdRoute
  AdminPanelClientsNewRoute: typeof AdminPanelClientsNewRoute
}

const AdminPanelClientsRouteChildren: AdminPanelClientsRouteChildren = {
  AdminPanelClientsClientIdRoute: AdminPanelClientsClientIdRoute,
  AdminPanelClientsNewRoute: AdminPanelClientsNewRoute,
}

const AdminPanelClientsRouteWithChildren =
  AdminPanelClientsRoute._addFileChildren(AdminPanelClientsRouteChildren)

interface AdminPanelInvoicesRouteChildren {
  AdminPanelInvoicesInvoiceIdRoute: typeof AdminPanelInvoicesInvoiceIdRoute
  AdminPanelInvoicesNewRoute: typeof AdminPanelInvoicesNewRoute
}

const AdminPanelInvoicesRouteChildren: AdminPanelInvoicesRouteChildren = {
  AdminPanelInvoicesInvoiceIdRoute: AdminPanelInvoicesInvoiceIdRoute,
  AdminPanelInvoicesNewRoute: AdminPanelInvoicesNewRoute,
}

const AdminPanelInvoicesRouteWithChildren =
  AdminPanelInvoicesRoute._addFileChildren(AdminPanelInvoicesRouteChildren)

interface AdminPanelProjectsRouteChildren {
  AdminPanelProjectsProjectIdRoute: typeof AdminPanelProjectsProjectIdRoute
  AdminPanelProjectsNewRoute: typeof AdminPanelProjectsNewRoute
}

const AdminPanelProjectsRouteChildren: AdminPanelProjectsRouteChildren = {
  AdminPanelProjectsProjectIdRoute: AdminPanelProjectsProjectIdRoute,
  AdminPanelProjectsNewRoute: AdminPanelProjectsNewRoute,
}

const AdminPanelProjectsRouteWithChildren =
  AdminPanelProjectsRoute._addFileChildren(AdminPanelProjectsRouteChildren)

interface AdminPanelQuotationsRouteChildren {
  AdminPanelQuotationsQuotationIdRoute: typeof AdminPanelQuotationsQuotationIdRoute
  AdminPanelQuotationsNewRoute: typeof AdminPanelQuotationsNewRoute
}

const AdminPanelQuotationsRouteChildren: AdminPanelQuotationsRouteChildren = {
  AdminPanelQuotationsQuotationIdRoute: AdminPanelQuotationsQuotationIdRoute,
  AdminPanelQuotationsNewRoute: AdminPanelQuotationsNewRoute,
}

const AdminPanelQuotationsRouteWithChildren =
  AdminPanelQuotationsRoute._addFileChildren(AdminPanelQuotationsRouteChildren)

interface AdminPanelRouteChildren {
  AdminPanelBillingRoute: typeof AdminPanelBillingRoute
  AdminPanelCatalogRoute: typeof AdminPanelCatalogRoute
  AdminPanelClientsRoute: typeof AdminPanelClientsRouteWithChildren
  AdminPanelDashboardRoute: typeof AdminPanelDashboardRoute
  AdminPanelDocumentsRoute: typeof AdminPanelDocumentsRoute
  AdminPanelExpensesRoute: typeof AdminPanelExpensesRoute
  AdminPanelInvoicesRoute: typeof AdminPanelInvoicesRouteWithChildren
  AdminPanelPaymentsRoute: typeof AdminPanelPaymentsRoute
  AdminPanelProjectsRoute: typeof AdminPanelProjectsRouteWithChildren
  AdminPanelQuotationsRoute: typeof AdminPanelQuotationsRouteWithChildren
  AdminPanelSettingsRoute: typeof AdminPanelSettingsRoute
}

const AdminPanelRouteChildren: AdminPanelRouteChildren = {
  AdminPanelBillingRoute: AdminPanelBillingRoute,
  AdminPanelCatalogRoute: AdminPanelCatalogRoute,
  AdminPanelClientsRoute: AdminPanelClientsRouteWithChildren,
  AdminPanelDashboardRoute: AdminPanelDashboardRoute,
  AdminPanelDocumentsRoute: AdminPanelDocumentsRoute,
  AdminPanelExpensesRoute: AdminPanelExpensesRoute,
  AdminPanelInvoicesRoute: AdminPanelInvoicesRouteWithChildren,
  AdminPanelPaymentsRoute: AdminPanelPaymentsRoute,
  AdminPanelProjectsRoute: AdminPanelProjectsRouteWithChildren,
  AdminPanelQuotationsRoute: AdminPanelQuotationsRouteWithChildren,
  AdminPanelSettingsRoute: AdminPanelSettingsRoute,
}

const AdminPanelRouteWithChildren = AdminPanelRoute._addFileChildren(
  AdminPanelRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminPanelRoute: AdminPanelRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
